tunnel: 1d5fea2a-d9b2-4ad9-baa7-b952aa47efdf
credentials-file: .cloudflared/1d5fea2a-d9b2-4ad9-baa7-b952aa47efdf.json

ingress:
  - hostname: api.classmaster.top
    service: http://localhost:4000
  - service: http_status:404
