services:
  # PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: classmaster

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: pgadmin-ui
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      db:
        condition: service_healthy
    user: "0:0"

    volumes:
      - ./classmaster_data/pgadmin_data:/var/lib/pgadmin
      - ./classmaster_data:/var/lib/pgadmin/storage/admin_admin.com/backups

  # MinIO
  minio:
    image: quay.io/minio/minio:latest
    container_name: local-minio

    restart: always

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    command: server /data --console-address ":9001"

    volumes:
      - ./classmaster_data/s3_storage:/data
  # API
  api:
    build: .
    container_name: api

    restart: always

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/classmaster?schema=public
      MINIO_ENDPOINT: http://local-minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password123
      MINIO_BUCKET_NAME: classmaster

    ports:
      - "4000:4000"

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - .:/app
      - /app/node_modules
      - ./classmaster_data/backups:/app/backups

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:2025.5.0
    container_name: cloudflare_tunnel

    restart: always

    depends_on:
      - api

    volumes:
      - ./.cloudflared:/etc/cloudflared

    command: tunnel --config /etc/cloudflared/config.yml run

volumes:
  pgdata:
  pgadmin_data:
